// <auto-generated />
using System;
using Bazzuca.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bazzuca.Infra.Migrations
{
    [DbContext(typeof(BazzucaContext))]
    partial class BazzucaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bazzuca.Infra.Context.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ClientId")
                        .HasName("clients_pkey");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.Post", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PostId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<int>("PostType")
                        .HasColumnType("integer")
                        .HasColumnName("post_type");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("s3_key");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("schedule_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.HasKey("PostId")
                        .HasName("posts_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("NetworkId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.SocialNetwork", b =>
                {
                    b.Property<long>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NetworkId"));

                    b.Property<string>("AccessSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_secret");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_token");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<int>("NetworkKey")
                        .HasColumnType("integer")
                        .HasColumnName("network_key");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("url");

                    b.Property<string>("User")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user");

                    b.HasKey("NetworkId")
                        .HasName("social_networks_pkey");

                    b.HasIndex("ClientId");

                    b.ToTable("social_networks", (string)null);
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.Post", b =>
                {
                    b.HasOne("Bazzuca.Infra.Context.Client", "Client")
                        .WithMany("Posts")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_post");

                    b.HasOne("Bazzuca.Infra.Context.SocialNetwork", "Network")
                        .WithMany("Posts")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_network_post");

                    b.Navigation("Client");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.SocialNetwork", b =>
                {
                    b.HasOne("Bazzuca.Infra.Context.Client", "Client")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_client_social_network");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.Client", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("SocialNetworks");
                });

            modelBuilder.Entity("Bazzuca.Infra.Context.SocialNetwork", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
